import Image from "next/image";
import { createClient } from "@supabase/supabase-js";
import PageShell from "../../components/PageShell";
import { mascotForTeam } from "../../lib/teamMascots";

export const dynamic = "force-dynamic";
const ESPN_LEAGUE_ID="2145514194",SEASON=2026;
const normalize=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"");
function espnTeamName(t){if(!t)return"Unknown Team";if(t.name)return t.name;return[t.location,t.nickname].filter(Boolean).join(" ").trim()||t.abbrev||`ESPN Team ${t.id}`;}
async function getTeams(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!u||!k)return[];const s=createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}});const{data}=await s.from("teams").select("id,name,manager,short_name,logo").order("id");return data||[];}
async function getEspnMatchups(){const u=new URL(`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${SEASON}/segments/0/leagues/${ESPN_LEAGUE_ID}`);u.searchParams.append("view","mTeam");u.searchParams.append("view","mMatchupScore");const h={accept:"application/json, text/plain, */*","user-agent":"DirtyDozensFFL/1.0"};if(process.env.ESPN_S2&&process.env.ESPN_SWID)h.cookie=`espn_s2=${process.env.ESPN_S2}; SWID=${process.env.ESPN_SWID}`;const r=await fetch(u,{headers:h,cache:"no-store"});if(!r.ok)throw new Error(`ESPN returned ${r.status}`);const d=await r.json(),week=Number(d?.status?.currentMatchupPeriod||1),byId=new Map((d?.teams||[]).map(t=>[Number(t.id),t]));return{week,matchups:(d?.schedule||[]).filter(g=>Number(g.matchupPeriodId)===week&&g.home&&g.away).map(g=>({id:`espn-${g.id}`,team1_name:espnTeamName(byId.get(Number(g.home.teamId))),team2_name:espnTeamName(byId.get(Number(g.away.teamId))),team1_score:g.home.totalPoints==null?null:Number(g.home.totalPoints),team2_score:g.away.totalPoints==null?null:Number(g.away.totalPoints),completed:Boolean(g.winner&&g.winner!=="UNDECIDED")}))};}
async function getSavedMatchups(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!u||!k)return{matchups:[],week:1};const s=createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}}),{data}=await s.from("matchups").select("*").eq("season",SEASON).order("week",{ascending:false}).order("id"),week=data?.length?Math.max(...data.map(m=>Number(m.week))):1;return{matchups:(data||[]).filter(m=>Number(m.week)===week),week};}

export default async function Matchups(){const teams=await getTeams(),byName=Object.fromEntries(teams.map(t=>[normalize(t.name),t])),byId=Object.fromEntries(teams.map(t=>[t.id,t]));let source="ESPN LIVE",week=1,matchups=[];try{const e=await getEspnMatchups();week=e.week;matchups=e.matchups;}catch{const s=await getSavedMatchups();week=s.week;source="SAVED RESULTS";matchups=s.matchups.map(m=>({...m,team1_name:byId[m.team1_id]?.name||"Team",team2_name:byId[m.team2_id]?.name||"Team"}));}
return <PageShell title="MATCHUPS" kicker="2026 SEASON">{matchups.length?<><div className="weekSummary"><div><span>WEEK</span><strong>{week}</strong></div><b>{source}</b></div><div className="matchupGrid publicMatchupGrid">{matchups.map(m=>{const h=byName[normalize(m.team1_name)],a=byName[normalize(m.team2_name)],s1=m.team1_score==null?null:Number(m.team1_score),s2=m.team2_score==null?null:Number(m.team2_score);return <article className="panel publicMatchupCard mascotMatchup" key={m.id}><div className={`publicTeamRow ${s1!=null&&s2!=null&&s1>s2?"winner":""}`}><div className="matchupIdentity"><div className="miniMascot"><Image src={mascotForTeam(m.team1_name,h?.logo||"")} alt="" width={70} height={70}/></div><div><strong>{m.team1_name}</strong><small>{h?.manager||""}</small></div></div><b>{s1==null?"—":s1.toFixed(1)}</b></div><div className="matchupStatus">{m.completed?"FINAL":"LIVE / SCHEDULED"}</div><div className={`publicTeamRow ${s1!=null&&s2!=null&&s2>s1?"winner":""}`}><div className="matchupIdentity"><div className="miniMascot"><Image src={mascotForTeam(m.team2_name,a?.logo||"")} alt="" width={70} height={70}/></div><div><strong>{m.team2_name}</strong><small>{a?.manager||""}</small></div></div><b>{s2==null?"—":s2.toFixed(1)}</b></div></article>})}</div></>:<section className="panel emptyPage"><h2>WEEK {week} SCHEDULE PENDING</h2><p>The ESPN schedule will appear here automatically as soon as it is available.</p></section>}</PageShell>;
}
