import Image from "next/image";
import Link from "next/link";
import { createClient } from "@supabase/supabase-js";
import Header from "../components/Header";
import { league, records, headlines } from "../data/league";
import { mascotForTeam } from "../lib/teamMascots";

export const dynamic = "force-dynamic";
const ESPN_LEAGUE_ID="2145514194",SEASON=2026;
const normalize=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"");
function espnTeamName(t){if(!t)return"Unknown Team";if(t.name)return t.name;return[t.location,t.nickname].filter(Boolean).join(" ").trim()||t.abbrev||`ESPN Team ${t.id}`;}
async function getEspnLeague(){const u=new URL(`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${SEASON}/segments/0/leagues/${ESPN_LEAGUE_ID}`);for(const v of["mTeam","mMatchupScore","mStandings"])u.searchParams.append("view",v);const h={accept:"application/json, text/plain, */*","user-agent":"DirtyDozensFFL/1.0"};if(process.env.ESPN_S2&&process.env.ESPN_SWID)h.cookie=`espn_s2=${process.env.ESPN_S2}; SWID=${process.env.ESPN_SWID}`;const r=await fetch(u,{headers:h,cache:"no-store"});if(!r.ok)throw new Error(`ESPN returned ${r.status}`);const d=await r.json(),week=Number(d?.status?.currentMatchupPeriod||1),teams=d?.teams||[],schedule=d?.schedule||[],byId=new Map(teams.map(t=>[Number(t.id),t]));return{week,teams,schedule,matchups:schedule.filter(g=>Number(g.matchupPeriodId)===week&&g.home&&g.away).map(g=>({id:`espn-${g.id}`,team1_name:espnTeamName(byId.get(Number(g.home.teamId))),team2_name:espnTeamName(byId.get(Number(g.away.teamId))),team1_score:g.home.totalPoints==null?null:Number(g.home.totalPoints),team2_score:g.away.totalPoints==null?null:Number(g.away.totalPoints),completed:Boolean(g.winner&&g.winner!=="UNDECIDED")}))};}
function buildHighScores(teams,schedule,currentWeek){const byId=new Map(teams.map(t=>[Number(t.id),t])),w=[];for(let week=1;week<=currentWeek;week++){const e=[];for(const g of schedule){if(Number(g.matchupPeriodId)!==week)continue;if(g.home?.teamId&&g.home.totalPoints!=null)e.push({team:byId.get(Number(g.home.teamId)),score:Number(g.home.totalPoints)});if(g.away?.teamId&&g.away.totalPoints!=null)e.push({team:byId.get(Number(g.away.teamId)),score:Number(g.away.totalPoints)});}if(e.length){e.sort((a,b)=>b.score-a.score);w.push({week,name:espnTeamName(e[0].team),score:e[0].score,live:week===currentWeek});}}return w.sort((a,b)=>b.week-a.week);}
function buildAutoPowerRankings(ts,schedule,currentWeek){const base=ts.map(t=>{const o=t?.record?.overall||{},g=Number(o.wins||0)+Number(o.losses||0)+Number(o.ties||0);return{espnTeamId:Number(t.id),name:espnTeamName(t),wins:Number(o.wins||0),losses:Number(o.losses||0),winPct:g?(Number(o.wins||0)+Number(o.ties||0)*.5)/g:0,pointsFor:Number(o.pointsFor||0),qualityWins:0};}),byId=Object.fromEntries(base.map(t=>[t.espnTeamId,t]));for(const g of schedule){if(!g?.home||!g?.away||Number(g.matchupPeriodId)>=currentWeek)continue;const h=byId[Number(g.home.teamId)],a=byId[Number(g.away.teamId)];if(!h||!a)continue;const hs=Number(g.home.totalPoints||0),as=Number(g.away.totalPoints||0);if(hs>as)h.qualityWins+=a.winPct;else if(as>hs)a.qualityWins+=h.winPct;}const maxPF=Math.max(...base.map(t=>t.pointsFor),1),maxQ=Math.max(...base.map(t=>t.qualityWins),1);return base.map(t=>({...t,powerScore:t.winPct*.45+(t.pointsFor/maxPF)*.40+(t.qualityWins/maxQ)*.15})).sort((a,b)=>b.powerScore-a.powerScore||b.pointsFor-a.pointsFor||b.wins-a.wins).map((t,i)=>({...t,rank:i+1}));}
async function getLiveLeagueData(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!u||!k)return{teams:[],matchups:[],highScores:[],news:[],dirtyPlayer:null,week:1,matchupSource:"SAVED RESULTS",powerRankings:[],powerSource:"AUTO"};const s=createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}}),[teamsRes,matchupsRes,highRes,newsRes,dirtyRes,rankingsRes]=await Promise.all([s.from("teams").select("*"),s.from("matchups").select("*").eq("season",SEASON).order("week",{ascending:false}).order("id"),s.from("weekly_high_scores").select("*").eq("season",SEASON).order("week",{ascending:false}),s.from("league_news").select("id,title,body,published_at").order("published_at",{ascending:false}).limit(3),s.from("dirty_players").select("*").eq("season",SEASON).order("week",{ascending:false}).limit(1),s.from("power_rankings").select("*").eq("season",SEASON).order("week",{ascending:false}).order("rank")]);const teams=teamsRes.data||[],all=matchupsRes.data||[],savedWeek=all.length?Math.max(...all.map(m=>Number(m.week))):1,byId=Object.fromEntries(teams.map(t=>[t.id,t]));let week=savedWeek,matchupSource="SAVED RESULTS",powerSource="AUTO — ESPN STATS",highScores=(highRes.data||[]).map(e=>({...e,name:byId[e.team_id]?.name||"Team",live:false})),powerRankings=[],matchups=all.filter(m=>Number(m.week)===savedWeek).map(m=>({...m,team1_name:byId[m.team1_id]?.name||"Team",team2_name:byId[m.team2_id]?.name||"Team"}));try{const e=await getEspnLeague();if(e.matchups.length){week=e.week;matchups=e.matchups;matchupSource="ESPN LIVE";}highScores=buildHighScores(e.teams,e.schedule,e.week);const auto=buildAutoPowerRankings(e.teams,e.schedule,e.week),rows=(rankingsRes.data||[]).filter(r=>Number(r.week)===e.week).sort((a,b)=>Number(a.rank)-Number(b.rank));if(rows.length===12){powerSource="COMMISSIONER EDITED";powerRankings=rows.map(r=>({rank:r.rank,name:byId[r.team_id]?.name||"Team"}));}else powerRankings=auto;}catch{const saved=rankingsRes.data||[],rw=saved.length?Math.max(...saved.map(r=>Number(r.week))):null;if(rw){powerSource="COMMISSIONER EDITED";powerRankings=saved.filter(r=>Number(r.week)===rw).sort((a,b)=>Number(a.rank)-Number(b.rank)).map(r=>({rank:r.rank,name:byId[r.team_id]?.name||"Team"}));}}return{teams,matchups,highScores,news:newsRes.data||[],dirtyPlayer:dirtyRes.data?.[0]||null,week,matchupSource,powerRankings,powerSource};}

function TinyMascot({name,team,size=42}){const src=mascotForTeam(name,team?.logo||"");return src?<span className="homeMascot"><Image src={src} alt="" width={size} height={size}/></span>:null;}
export default async function Home(){const live=await getLiveLeagueData(),byId=Object.fromEntries(live.teams.map(t=>[t.id,t])),byName=Object.fromEntries(live.teams.map(t=>[normalize(t.name),t])),standings=[...live.teams].sort((a,b)=>Number(b.wins||0)-Number(a.wins||0)||Number(b.points_for||0)-Number(a.points_for||0)||String(a.name).localeCompare(String(b.name))),homepageNews=live.news.length?live.news.map(i=>({title:i.title,deck:i.body||""})):headlines,dirtyTeam=live.dirtyPlayer?byId[live.dirtyPlayer.team_id]:null;
return <><div className="topline">{league.tagline}</div><Header/><main className="homeGrid pageWrap"><section className="pageHero homeHero"><div className="heroCopy"><span className="eyebrow">WELCOME TO</span><h1>DIRTY DOZENS <em>FFL</em></h1><p>{league.subtagline}</p><Link className="button" href="/teams">Meet the Dirty Dozen →</Link></div><div className="heroMark">12</div></section><section className="panel championCard"><span className="eyebrow">DEFENDING CHAMPION</span><h2>{league.defendingChampion}</h2><strong>{league.defendingChampionManager}</strong><div className="belt">CHAMPION</div><p>{league.defendingChampionSeason} SEASON</p></section><section className="panel matchupFeature"><div className="panelTitle"><h3>WEEK {live.week}</h3><span>{live.matchupSource}</span></div>{live.matchups.length?<div className="pendingState"><strong>{live.matchups.every(m=>m.completed)?"RESULTS POSTED":"LIVE MATCHUPS"}</strong><p>{live.matchups.length} matchups are updating from ESPN for Week {live.week}.</p></div>:<div className="pendingState"><strong>SCHEDULE PENDING</strong><p>The official ESPN matchups will appear automatically.</p></div>}<Link className="ghostButton" href="/matchups">View matchups</Link></section>
<section className="panel span2 matchupPanel"><div className="panelTitle"><h3>WEEK {live.week} MATCHUPS</h3><span>{live.matchupSource}</span><Link href="/matchups">VIEW ALL</Link></div>{live.matchups.length?<div className="matchupList">{live.matchups.map(m=>{const t1=m.team1_name?byName[normalize(m.team1_name)]:byId[m.team1_id],t2=m.team2_name?byName[normalize(m.team2_name)]:byId[m.team2_id],n1=m.team1_name||t1?.name||"Team",n2=m.team2_name||t2?.name||"Team",s1=m.team1_score==null?null:Number(m.team1_score),s2=m.team2_score==null?null:Number(m.team2_score);return <article className="homeMatchup mascotHomeMatchup" key={m.id}><div className={`homeMatchupTeam ${s1!=null&&s2!=null&&s1>s2?"winner":""}`}><span className="homeTeamName"><TinyMascot name={n1} team={t1}/>{n1}</span><strong>{s1==null?"—":s1.toFixed(1)}</strong></div><div className="homeMatchupStatus">{m.completed?"FINAL":live.matchupSource==="ESPN LIVE"?"LIVE / SCHEDULED":"SCHEDULED"}</div><div className={`homeMatchupTeam ${s1!=null&&s2!=null&&s2>s1?"winner":""}`}><span className="homeTeamName"><TinyMascot name={n2} team={t2}/>{n2}</span><strong>{s2==null?"—":s2.toFixed(1)}</strong></div></article>})}</div>:<div className="emptyPanel">Official Week {live.week} matchups have not been added yet.</div>}</section>
<section className="panel span2 highScoreTracker"><div className="panelTitle"><h3>WEEKLY HIGH SCORE</h3><span>ESPN AUTO</span></div>{live.highScores.length?<div className="highScoreList">{live.highScores.map(e=>{const n=e.name||byId[e.team_id]?.name||"Team",t=byName[normalize(n)]||byId[e.team_id];return <div className="highScoreItem" key={e.week}><span>WEEK {e.week}{e.live?" · LIVE":""}</span><strong className="homeTeamName"><TinyMascot name={n} team={t}/>{n}</strong><b>{Number(e.score).toFixed(1)}</b></div>})}</div>:<div className="emptyPanel">The weekly scoring leader will appear automatically when ESPN scores are available.</div>}</section>
<section className="panel standingsPanel"><div className="panelTitle"><h3>STANDINGS</h3><Link href="/standings">FULL</Link></div>{standings.length?<div className="standingsScroll"><table><thead><tr><th>#</th><th>Team</th><th>W</th><th>L</th><th>PF</th></tr></thead><tbody>{standings.slice(0,8).map((t,i)=><tr key={t.id}><td>{i+1}</td><td><span className="homeTeamName"><TinyMascot name={t.name} team={t}/>{t.name}</span></td><td>{t.wins??0}</td><td>{t.losses??0}</td><td>{Number(t.points_for||0).toFixed(1)}</td></tr>)}</tbody></table></div>:<div className="emptyPanel">Standings will appear here once league data is available.</div>}</section>
<section className="panel rankingsPanel"><div className="panelTitle"><h3>POWER RANKINGS</h3><span>{live.powerSource}</span><Link href="/power-rankings">FULL</Link></div>{live.powerRankings.length?<div>{live.powerRankings.slice(0,5).map(r=>{const t=byName[normalize(r.name)];return <div className="recordRow mascotRecordRow" key={`${r.rank}-${r.name}`}><span className="homeTeamName"><TinyMascot name={r.name} team={t}/>#{r.rank} {r.name}</span><strong>{r.pointsFor!=null?`${Number(r.pointsFor).toFixed(1)} PF`:""}</strong></div>})}</div>:<div className="emptyPanel">Power rankings will calculate automatically from ESPN statistics.</div>}</section>
<section className="panel newsPanel"><div className="panelTitle"><h3>LEAGUE NEWS</h3><Link href="/news">VIEW ALL</Link></div>{homepageNews.map((h,i)=><article key={`${h.title}-${i}`}><span className="newsIndex">0{i+1}</span><div><h4>{h.title}</h4><p>{h.deck}</p></div></article>)}</section><section className="panel recordsPanel"><div className="panelTitle"><h3>RECORD BOOK</h3><Link href="/records">VIEW ALL</Link></div>{records.map(([l,v])=><div className="recordRow" key={l}><span>{l}</span><strong>{v}</strong></div>)}</section><section className="panel dirtyPlayer"><span className="eyebrow">DIRTY PLAYER OF THE WEEK</span><div className="trashIcon">★</div>{live.dirtyPlayer?<><h2>{live.dirtyPlayer.player_name}</h2><strong>{dirtyTeam?.name||"Dirty Dozens"} — WEEK {live.dirtyPlayer.week}</strong><p>{live.dirtyPlayer.reason||"Commissioner's choice."}</p></>:<><h2>COMING WEEK 1</h2><strong>WHO EARNS IT?</strong><p>The commissioner's weekly selection will be featured here.</p></>}</section><section className="panel trashTalk"><div className="panelTitle"><h3>TRASH TALK FEED</h3></div><blockquote>“Receipts will be kept.”</blockquote><blockquote>“Twelve teams. One trophy.”</blockquote><blockquote>“Nobody is safe from the weekly recap.”</blockquote></section></main><footer><strong>DIRTY DOZENS <span>FFL</span></strong><small>{league.subtagline}</small></footer></>;
}
