export const DEFAULT_PROFILE_BLOCKS=["story","personal_records","snapshot","all_time","current_highs","best_recent","head_to_head"];

const pct=value=>`${(Number(value||0)*100).toFixed(1)}%`;

export default function FranchiseProfileBlocks({layoutOrder,personalRecords,allTime,current,titles,currentSeason,startSeason}){
  const allGames=allTime.wins+allTime.losses+allTime.ties;
  const allRecord=`${allTime.wins}-${allTime.losses}${allTime.ties?`-${allTime.ties}`:""}`;
  const currentRecord=`${current.wins}-${current.losses}${current.ties?`-${current.ties}`:""}`;
  const ordered=[...new Set([...(Array.isArray(layoutOrder)?layoutOrder:[]),...DEFAULT_PROFILE_BLOCKS])].filter(id=>DEFAULT_PROFILE_BLOCKS.includes(id));

  const blocks={
    story:<section className="panel franchiseStoryCard" key="story"><div className="panelTitle"><h3>FRANCHISE STORY</h3><span>FROM THE OWNER</span></div>{allTime.profileStory?<p>{allTime.profileStory}</p>:<div className="emptyPanel">No franchise story has been added yet.</div>}</section>,
    personal_records:<section className="panel franchisePersonalRecords" key="personal_records"><div className="panelTitle"><h3>PERSONAL RECORDS</h3><span>OWNER CURATED</span></div>{personalRecords?.length?<div className="personalRecordGrid">{personalRecords.map(record=><article key={record.id} className="personalRecordItem"><small>{record.season?`${record.season}${record.week?` · WEEK ${record.week}`:""}`:"FRANCHISE RECORD"}</small><strong>{record.record_value}</strong><h4>{record.title}</h4>{record.note?<p>{record.note}</p>:null}</article>)}</div>:<div className="emptyPanel">This manager has not added personal records yet.</div>}</section>,
    snapshot:<section className="panel franchiseSnapshotCard" key="snapshot"><div className="panelTitle"><h3>FRANCHISE SNAPSHOT</h3><span>{startSeason}–{currentSeason}</span></div><div className="franchiseSnapshotStats"><div><small>CAREER RECORD</small><strong>{allRecord}</strong></div><div><small>WIN RATE</small><strong>{allGames?pct((allTime.wins+allTime.ties*.5)/allGames):"—"}</strong></div><div><small>ALL-TIME PF</small><strong>{allTime.pf.toFixed(1)}</strong></div><div><small>AVG SCORE</small><strong>{allGames?(allTime.pf/allGames).toFixed(1):"—"}</strong></div></div></section>,
    all_time:<section key="all_time"><div className="panelTitle franchiseSectionTitle"><h3>ALL-TIME FRANCHISE</h3><span>{allGames} COMPLETED GAMES</span></div><div className="recordCards franchiseRecordCards">{[["CAREER RECORD",allRecord],["WIN %",allGames?pct((allTime.wins+allTime.ties*.5)/allGames):"—"],["ALL-TIME PF",allTime.pf.toFixed(1)],["AVG SCORE",allGames?(allTime.pf/allGames).toFixed(1):"—"],["TITLES",String(titles)],["SEASONS",String(allTime.seasons.length)]].map(([label,value])=><article className="panel recordCard" key={label}><h3>{label}</h3><strong>{value}</strong></article>)}</div></section>,
    current_highs:<div className="commissionerGrid franchiseDataGrid" key="current_highs"><section className="panel"><div className="panelTitle"><h3>CURRENT SEASON</h3><span>{currentSeason} · WEEK {current.week}</span></div><div className="franchiseDataList"><div><small>RECORD</small><strong>{currentRecord}</strong></div><div><small>POWER RANK</small><strong>{current.rank?`#${current.rank}`:"—"}</strong></div><div><small>POINTS FOR / AGAINST</small><strong>{current.pf.toFixed(1)} / {current.pa.toFixed(1)}</strong></div></div></section><section className="panel"><div className="panelTitle"><h3>ALL-TIME HIGHS</h3><span>ESPN ARCHIVE</span></div><div className="franchiseDataList"><div><small>HIGHEST SCORE</small><strong>{allTime.high?allTime.high.myScore.toFixed(1):"—"}</strong><p>{allTime.high?`${allTime.high.season} Wk ${allTime.high.week} vs ${allTime.high.opponent}`:"No archived result"}</p></div><div><small>BIGGEST WIN</small><strong>{allTime.biggest?`+${allTime.biggest.margin.toFixed(1)}`:"—"}</strong><p>{allTime.biggest?`${allTime.biggest.season} Wk ${allTime.biggest.week} vs ${allTime.biggest.opponent}`:"No archived win"}</p></div></div></section></div>,
    best_recent:<div className="commissionerGrid franchiseDataGrid" key="best_recent"><section className="panel"><div className="panelTitle"><h3>BEST SEASON</h3><span>BY WIN %</span></div>{allTime.bestSeason?<div className="bestSeasonBlock"><strong>{allTime.bestSeason.season}</strong><p>{allTime.bestSeason.wins}-{allTime.bestSeason.losses}{allTime.bestSeason.ties?`-${allTime.bestSeason.ties}`:""} · {pct(allTime.bestSeason.winPct)} · {allTime.bestSeason.pf.toFixed(1)} PF</p></div>:<p>No season history available.</p>}</section><section className="panel"><div className="panelTitle"><h3>RECENT RESULTS</h3><span>LATEST 5</span></div>{allTime.games.slice(0,5).length?<div className="franchiseRecentList">{allTime.games.slice(0,5).map(game=><div key={`${game.season}-${game.week}-${game.opponent}`}><b className={`resultChip result${game.result}`}>{game.result}</b><span>{game.season} Wk {game.week} · {game.opponent}</span><strong>{game.myScore.toFixed(1)}-{game.oppScore.toFixed(1)}</strong></div>)}</div>:<p>No completed archived games.</p>}</section></div>,
    head_to_head:<section className="panel franchiseHeadToHead" key="head_to_head"><div className="panelTitle"><h3>ALL-TIME HEAD-TO-HEAD</h3><span>BY MANAGER</span></div>{allTime.opponents.length?<div className="franchiseHeadRows">{allTime.opponents.map(opponent=><div key={String(opponent.opponent).toLowerCase().replace(/[^a-z0-9]/g,"")}><div><strong>{opponent.opponent}</strong><small>{opponent.meetings} meetings · {opponent.pf.toFixed(1)} PF / {opponent.pa.toFixed(1)} PA</small></div><b>{opponent.w}-{opponent.l}{opponent.t?`-${opponent.t}`:""}</b></div>)}</div>:<div className="emptyPanel">Head-to-head history will appear here as archived matchups are available.</div>}</section>
  };

  return <div className="franchiseCustomBlocks">{ordered.map(id=>blocks[id])}</div>;
}
