import { createClient } from "@supabase/supabase-js";
import PageShell from "../../components/PageShell";
import styles from "./rivalries.module.css";

export const dynamic = "force-dynamic";
const ESPN_LEAGUE_ID="2145514194", CURRENT_SEASON=2026, START_SEASON=2022, MAP_RECORD="__OWNER_MAP__";
const normalize=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"");
function teamName(t){return t?.name||[t?.location,t?.nickname].filter(Boolean).join(" ").trim()||t?.abbrev||`Team ${t?.id||""}`;}
function headers(){const h={accept:"application/json, text/plain, */*","user-agent":"DirtyDozensFFL/1.0"};if(process.env.ESPN_S2&&process.env.ESPN_SWID)h.cookie=`espn_s2=${process.env.ESPN_S2}; SWID=${process.env.ESPN_SWID}`;return h;}
async function fetchSeason(season){const u=new URL(`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${season}/segments/0/leagues/${ESPN_LEAGUE_ID}`);for(const v of ["mTeam","mMatchupScore","mStatus"])u.searchParams.append("view",v);const r=await fetch(u,{headers:headers(),cache:"no-store"});if(!r.ok)throw new Error(String(r.status));return r.json();}
async function archive(){return (await Promise.all(Array.from({length:CURRENT_SEASON-START_SEASON+1},(_,i)=>START_SEASON+i).map(async season=>{try{return{season,data:await fetchSeason(season)}}catch{return null}}))).filter(Boolean);}
function owner(t,m){const x=m.get(t?.owners?.[0]);return x?.displayName||[x?.firstName,x?.lastName].filter(Boolean).join(" ")||"";}
function readable(n){const c=normalize(n);return !!c&&!/^espnfan\d+$/i.test(c)&&!/^[a-z]+\d{2,}$/i.test(c);}
async function local(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return{maps:new Map()};const s=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const [{data:teams},{data:rows}]=await Promise.all([s.from("teams").select("id,name,manager"),s.from("league_records").select("record_value,team_id").eq("record_name",MAP_RECORD)]);const byId=Object.fromEntries((teams||[]).map(t=>[t.id,t]));return{maps:new Map((rows||[]).map(r=>{const t=byId[r.team_id];return[normalize(r.record_value),t?{manager:t.manager||t.name,team:t.name}:null]}).filter(([,v])=>v))};}
function build(a,l){const people=new Map(),pairs=new Map();const ensure=(manager,team="")=>{const k=normalize(manager);if(!people.has(k))people.set(k,{key:k,manager,team});const p=people.get(k);if(team)p.team=team;return p;};for(const {season,data} of a){const members=new Map((data?.members||[]).map(m=>[m.id,m])),byId=new Map();for(const t of data?.teams||[]){const raw=owner(t,members),mapped=l.maps.get(normalize(raw)),manager=mapped?.manager||(readable(raw)?raw:"");if(manager){const p=ensure(manager,mapped?.team||teamName(t));byId.set(Number(t.id),p.key);}}for(const g of data?.schedule||[]){if(!g?.home||!g?.away||!g.winner||g.winner==="UNDECIDED")continue;const hk=byId.get(Number(g.home.teamId)),ak=byId.get(Number(g.away.teamId));if(!hk||!ak||hk===ak)continue;const hs=Number(g.home.totalPoints),as=Number(g.away.totalPoints);if(!Number.isFinite(hs)||!Number.isFinite(as))continue;const keys=[hk,ak].sort(),id=keys.join("::");if(!pairs.has(id))pairs.set(id,{id,aKey:keys[0],bKey:keys[1],meetings:0,aWins:0,bWins:0,ties:0,aPts:0,bPts:0,totalMargin:0,closest:null,biggest:null,last:null});const p=pairs.get(id);p.meetings++;const hIsA=hk===p.aKey,aScore=hIsA?hs:as,bScore=hIsA?as:hs;p.aPts+=aScore;p.bPts+=bScore;const margin=Math.abs(hs-as);p.totalMargin+=margin;if(aScore>bScore)p.aWins++;else if(bScore>aScore)p.bWins++;else p.ties++;const game={season,week:Number(g.matchupPeriodId||0),aScore,bScore,margin,winner:aScore>bScore?p.aKey:bScore>aScore?p.bKey:"tie"};if(!p.closest||margin<p.closest.margin)p.closest=game;if(!p.biggest||margin>p.biggest.margin)p.biggest=game;if(!p.last||season>p.last.season||(season===p.last.season&&game.week>p.last.week))p.last=game;}}
const list=[...pairs.values()].map(p=>({...p,a:people.get(p.aKey),b:people.get(p.bKey),avgMargin:p.totalMargin/p.meetings,totalPoints:p.aPts+p.bPts})).filter(p=>p.a&&p.b);const most=[...list].sort((x,y)=>y.meetings-x.meetings||x.avgMargin-y.avgMargin),closest=[...list].sort((x,y)=>x.avgMargin-y.avgMargin||y.meetings-x.meetings),lopsided=[...list].sort((x,y)=>Math.abs(y.aWins-y.bWins)-Math.abs(x.aWins-x.bWins)||y.meetings-x.meetings);return{most,closest,lopsided,seasons:a.map(x=>x.season)};}
function Rivalry({p,rank}){return <article className={`panel ${styles.card}`}><div className={styles.rank}>RIVALRY #{rank}</div><div className={styles.matchup}><div className={styles.side}><small>{p.a.team||"Franchise"}</small><strong>{p.a.manager}</strong><b>{p.aWins}</b></div><span className={styles.vs}>VS</span><div className={styles.side}><small>{p.b.team||"Franchise"}</small><strong>{p.b.manager}</strong><b>{p.bWins}</b></div></div><div className={styles.meta}><span>{p.meetings} meetings</span><span>{p.ties?`${p.ties} tie${p.ties===1?"":"s"}`:"No ties"}</span><span>{p.avgMargin.toFixed(1)} avg margin</span></div>{p.last?<p className={styles.last}>Last meeting · {p.last.season} Week {p.last.week} · {p.last.aScore.toFixed(1)}–{p.last.bScore.toFixed(1)}</p>:null}</article>}
function RivalryRow({p,rank,mode}){return <div className={styles.row}><b>#{rank}</b><div><strong>{p.a.manager} vs {p.b.manager}</strong><small>{p.meetings} meetings{mode==="closest"?` · series ${p.aWins}-${p.bWins}${p.ties?`-${p.ties}`:""}`:""}</small></div><span>{mode==="closest"?p.avgMargin.toFixed(1):`${p.aWins}-${p.bWins}`}</span></div>}
export default async function Rivalries(){const [a,l]=await Promise.all([archive(),local()]),d=build(a,l),label=d.seasons.length?`${Math.min(...d.seasons)}–${Math.max(...d.seasons)}`:"ESPN ARCHIVE",featured=d.most[0];return <PageShell title="RIVALRY CENTER" kicker="BAD BLOOD · BRAGGING RIGHTS · HISTORY"><section className={`panel ${styles.hero}`}><div className={styles.heroCopy}><span className="eyebrow">HEAD-TO-HEAD ARCHIVE · {label}</span><h2>Every matchup leaves a receipt.</h2><p>Completed ESPN games are turned into an all-time head-to-head history so the league can see who really owns the bragging rights.</p></div>{featured?<div className={styles.feature}><span>MOST PLAYED RIVALRY</span><strong>{featured.a.manager} <em>vs</em> {featured.b.manager}</strong><b>{featured.aWins}–{featured.bWins}{featured.ties?`–${featured.ties}`:""}</b><small>{featured.meetings} meetings · {featured.avgMargin.toFixed(1)} point average margin</small></div>:null}</section><section><div className={styles.sectionHead}><h2>Most Played</h2><span>ALL-TIME SERIES</span></div><div className={styles.grid}>{d.most.slice(0,6).map((p,i)=><Rivalry key={p.id} p={p} rank={i+1}/>)}</div></section><div className={styles.lists}><section className={`panel ${styles.listPanel}`}><div className={styles.listTitle}><h3>CLOSEST RIVALRIES</h3><span>AVG MARGIN</span></div>{d.closest.slice(0,5).map((p,i)=><RivalryRow key={p.id} p={p} rank={i+1} mode="closest"/>)}</section><section className={`panel ${styles.listPanel}`}><div className={styles.listTitle}><h3>MOST ONE-SIDED</h3><span>SERIES EDGE</span></div>{d.lopsided.slice(0,5).map((p,i)=><RivalryRow key={p.id} p={p} rank={i+1} mode="lopsided"/>)}</section></div></PageShell>;}
