import Image from "next/image";
import { createClient } from "@supabase/supabase-js";
import PageShell from "../../components/PageShell";
import { mascotForTeam } from "../../lib/teamMascots";

export const dynamic="force-dynamic";
const ESPN_LEAGUE_ID="2145514194",SEASON=2026;
function espnTeamName(t){if(!t)return"Unknown Team";if(t.name)return t.name;return[t.location,t.nickname].filter(Boolean).join(" ").trim()||t.abbrev||`ESPN Team ${t.id}`;}
async function getLocalTeams(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!u||!k)return[];const s=createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}}),{data}=await s.from("teams").select("*");return data||[];}
async function getEspnStandings(){const u=new URL(`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${SEASON}/segments/0/leagues/${ESPN_LEAGUE_ID}`);u.searchParams.append("view","mTeam");u.searchParams.append("view","mStandings");const h={accept:"application/json, text/plain, */*","user-agent":"DirtyDozensFFL/1.0"};if(process.env.ESPN_S2&&process.env.ESPN_SWID)h.cookie=`espn_s2=${process.env.ESPN_S2}; SWID=${process.env.ESPN_SWID}`;const r=await fetch(u,{headers:h,cache:"no-store"});if(!r.ok)throw new Error(`ESPN returned ${r.status}`);const d=await r.json();return(d?.teams||[]).map(t=>{const o=t?.record?.overall||{};return{espnTeamId:Number(t.id),name:espnTeamName(t),wins:Number(o.wins||0),losses:Number(o.losses||0),ties:Number(o.ties||0),points_for:Number(o.pointsFor||0),points_against:Number(o.pointsAgainst||0),percentage:Number(o.percentage||0)};});}

export default async function Standings(){const local=await getLocalTeams(),byId=Object.fromEntries(local.map(t=>[Number(t.id),t]));let source="ESPN LIVE",teams;try{teams=(await getEspnStandings()).map(t=>{const localTeam=byId[t.espnTeamId];const name=localTeam?.name||t.name;return{...t,name,manager:localTeam?.manager||"",logo:mascotForTeam(name,localTeam?.logo||"")};});}catch{source="SAVED STANDINGS";teams=local.map(t=>{const g=Number(t.wins||0)+Number(t.losses||0)+Number(t.ties||0);return{...t,wins:Number(t.wins||0),losses:Number(t.losses||0),ties:Number(t.ties||0),points_for:Number(t.points_for||0),points_against:Number(t.points_against||0),percentage:g?(Number(t.wins||0)+Number(t.ties||0)*.5)/g:0,logo:mascotForTeam(t.name,t.logo)}});}teams.sort((a,b)=>Number(b.percentage||0)-Number(a.percentage||0)||Number(b.wins||0)-Number(a.wins||0)||Number(b.points_for||0)-Number(a.points_for||0)||String(a.name).localeCompare(String(b.name)));
return <PageShell title="STANDINGS" kicker="2026 SEASON"><div className="weekSummary"><div><span>DATA</span><strong>LIVE</strong></div><b>{source}</b></div>{teams.length?<div className="standingsList"><div className="standingsListHeader"><span>RK</span><span>TEAM</span><span>REC</span><span>PF</span><span>PA</span></div>{teams.map((t,i)=><article className="standingRow mascotStandingRow" key={t.espnTeamId||t.id||t.name}><div className="standingRank">{i+1}</div><div className="standingIdentity mascotStandingIdentity"><div className="standingMascot"><Image src={t.logo} alt="" width={64} height={64}/></div><div><strong>{t.name}</strong><small>{t.manager}</small></div></div><div className="standingRecord"><strong>{t.wins??0}-{t.losses??0}{Number(t.ties||0)?`-${t.ties}`:""}</strong><small>RECORD</small></div><div className="standingStat"><strong>{Number(t.points_for||0).toFixed(1)}</strong><small>PF</small></div><div className="standingStat"><strong>{Number(t.points_against||0).toFixed(1)}</strong><small>PA</small></div></article>)}</div>:<div className="panel emptyPanel">Standings will appear once league data is available.</div>}</PageShell>;
}
