import { createClient } from "@supabase/supabase-js";
import PageShell from "../../components/PageShell";

export const dynamic = "force-dynamic";
const ESPN_LEAGUE_ID="2145514194",SEASON=2026;
function headers(){const h={accept:"application/json, text/plain, */*","user-agent":"DirtyDozensFFL/1.0"};if(process.env.ESPN_S2&&process.env.ESPN_SWID)h.cookie=`espn_s2=${process.env.ESPN_S2}; SWID=${process.env.ESPN_SWID}`;return h;}
async function getLocalTeams(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!u||!k)return[];const s=createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}}),{data}=await s.from("teams").select("id,name,manager");return data||[];}
async function getEspn(){const u=new URL(`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${SEASON}/segments/0/leagues/${ESPN_LEAGUE_ID}`);for(const v of["mTeam","mStandings","mMatchupScore","mSettings","mStatus"])u.searchParams.append("view",v);const r=await fetch(u,{headers:headers(),cache:"no-store"});if(!r.ok)throw new Error(`ESPN returned ${r.status}`);return r.json();}
function espnName(t){return t?.name||[t?.location,t?.nickname].filter(Boolean).join(" ").trim()||t?.abbrev||`Team ${t?.id||""}`;}
function pct(v){return `${(Number(v||0)*100).toFixed(1)}%`;}
function buildRace(data,local){const byLocal=Object.fromEntries(local.map(t=>[Number(t.id),t])),raw=data?.teams||[],schedule=data?.schedule||[],settings=data?.settings?.scheduleSettings||{},currentWeek=Number(data?.status?.currentMatchupPeriod||1),regularWeeks=Number(settings.matchupPeriodCount||14),playoffTeams=Number(settings.playoffTeamCount||6),byeTeams=Number(settings.playoffByeCount||0);const teams=raw.map(t=>{const o=t?.record?.overall||{},wins=Number(o.wins||0),losses=Number(o.losses||0),ties=Number(o.ties||0),games=wins+losses+ties,localTeam=byLocal[Number(t.id)];return{id:Number(t.id),name:localTeam?.name||espnName(t),manager:localTeam?.manager||"",wins,losses,ties,games,winPct:games?(wins+ties*.5)/games:Number(o.percentage||0),pf:Number(o.pointsFor||0),pa:Number(o.pointsAgainst||0),streak:Number(o.streakLength||0),streakType:o.streakType||""};});const byId=Object.fromEntries(teams.map(t=>[t.id,t]));teams.sort((a,b)=>b.winPct-a.winPct||b.wins-a.wins||b.pf-a.pf||a.name.localeCompare(b.name));const cutoff=teams[Math.max(0,playoffTeams-1)]||null;const remaining=Math.max(0,regularWeeks-currentWeek);for(const [i,t] of teams.entries()){const opp=[];for(const g of schedule){const w=Number(g.matchupPeriodId||0);if(w<=currentWeek||w>regularWeeks||!g?.home||!g?.away)continue;const h=Number(g.home.teamId),a=Number(g.away.teamId);if(h===t.id&&byId[a])opp.push(byId[a]);else if(a===t.id&&byId[h])opp.push(byId[h]);}t.seed=i+1;t.remainingOpponents=opp;t.sos=opp.length?opp.reduce((sum,o)=>sum+o.winPct,0)/opp.length:0;t.gamesBack=cutoff?Math.max(0,(cutoff.wins+cutoff.ties*.5)-(t.wins+t.ties*.5)):0;t.maxWins=t.wins+remaining;t.status=currentWeek>regularWeeks?(i<playoffTeams?"PLAYOFF FIELD":"SEASON COMPLETE"):i<byeTeams?"BYE POSITION":i<playoffTeams?"IN FIELD":t.gamesBack<=1?"ON BUBBLE":"CHASING";}return{teams,currentWeek,regularWeeks,playoffTeams,byeTeams,remaining,cutoff};}
function RaceRow({t,playoffTeams}){return <article className={`playoffRaceRow ${t.seed===playoffTeams?"cutLine":""} ${t.seed<=playoffTeams?"inside":"outside"}`}><div className="playoffSeed">{t.seed}</div><div className="playoffIdentity"><strong>{t.name}</strong><small>{t.manager}</small></div><div className="playoffRecord"><strong>{t.wins}-{t.losses}{t.ties?`-${t.ties}`:""}</strong><small>RECORD</small></div><div className="playoffPf"><strong>{t.pf.toFixed(1)}</strong><small>PF</small></div><div className="playoffGb"><strong>{t.seed<=playoffTeams?"—":t.gamesBack.toFixed(1)}</strong><small>GB</small></div><div className="playoffSos"><strong>{t.remainingOpponents.length?pct(t.sos):"—"}</strong><small>REM. SOS</small></div><div className="playoffStatus"><b>{t.status}</b></div></article>}
export default async function PlayoffRace(){let race=null,error="";try{const [data,local]=await Promise.all([getEspn(),getLocalTeams()]);race=buildRace(data,local);}catch(e){error=e?.message||"Live playoff data unavailable";}return <PageShell title="PLAYOFF RACE" kicker="2026 ROAD TO THE TITLE"><section className="panel playoffHero"><span className="eyebrow">LIVE ESPN PLAYOFF PICTURE</span><h2>The race to survive the Dirty Dozens.</h2><p>Seeds use the current ESPN standings. The cut line, games back and remaining schedule strength update automatically as results change.</p>{race?<div className="playoffHeroStats"><div><span>CURRENT WEEK</span><strong>{race.currentWeek}</strong></div><div><span>PLAYOFF TEAMS</span><strong>{race.playoffTeams}</strong></div><div><span>REG. SEASON</span><strong>{race.regularWeeks} WKS</strong></div><div><span>WEEKS LEFT</span><strong>{race.remaining}</strong></div></div>:null}</section>{error?<section className="panel emptyPanel">{error}</section>:<><section className="panel playoffPicture"><div className="panelTitle"><h3>CURRENT PLAYOFF PICTURE</h3><span>ESPN LIVE</span></div><div className="playoffRaceHeader"><span>SEED</span><span>TEAM</span><span>REC</span><span>PF</span><span>GB</span><span>REM. SOS</span><span>STATUS</span></div>{race.teams.map(t=><RaceRow key={t.id} t={t} playoffTeams={race.playoffTeams}/>)}</section><div className="playoffBreakdown"><section className="panel"><div className="panelTitle"><h3>THE CUT LINE</h3><span>SEED #{race.playoffTeams}</span></div>{race.cutoff?<><h2>{race.cutoff.name}</h2><strong className="playoffBigNumber">{race.cutoff.wins}-{race.cutoff.losses}{race.cutoff.ties?`-${race.cutoff.ties}`:""}</strong><p>Currently holding the final playoff position with {race.cutoff.pf.toFixed(1)} points for.</p></>:null}</section><section className="panel"><div className="panelTitle"><h3>TOUGHEST ROAD</h3><span>REMAINING SOS</span></div>{[...race.teams].filter(t=>t.remainingOpponents.length).sort((a,b)=>b.sos-a.sos).slice(0,5).map((t,i)=><div className="playoffMiniRow" key={t.id}><b>#{i+1}</b><span><strong>{t.name}</strong><small>{t.remainingOpponents.length} games left</small></span><strong>{pct(t.sos)}</strong></div>)}</section><section className="panel"><div className="panelTitle"><h3>SOFTEST ROAD</h3><span>REMAINING SOS</span></div>{[...race.teams].filter(t=>t.remainingOpponents.length).sort((a,b)=>a.sos-b.sos).slice(0,5).map((t,i)=><div className="playoffMiniRow" key={t.id}><b>#{i+1}</b><span><strong>{t.name}</strong><small>{t.remainingOpponents.length} games left</small></span><strong>{pct(t.sos)}</strong></div>)}</section></div><section className="panel playoffNote"><strong>How this works</strong><p>“In Field” and “On Bubble” are live race labels, not mathematical clinches. Remaining SOS is the average current win percentage of scheduled regular-season opponents, so it changes throughout the year.</p></section></>}</PageShell>;}
