'use client';
import { useEffect,useMemo,useState } from 'react';
import PageShell from '../../components/PageShell';
import { getSupabase } from '../../lib/supabase';
const supabase=getSupabase();
const blankMatchups=()=>Array.from({length:6},()=>({team1_id:'',team2_id:'',team1_score:'',team2_score:''}));
const blankRankings=()=>Array.from({length:12},()=>({team_id:'',commentary:''}));
export default function CommissionerPage(){
 const[session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[status,setStatus]=useState(''),[teams,setTeams]=useState([]),[week,setWeek]=useState(1),[matchups,setMatchups]=useState(blankMatchups()),[dirtyPlayer,setDirtyPlayer]=useState({team_id:'',player_name:'',reason:''}),[news,setNews]=useState({title:'',body:''}),[rankings,setRankings]=useState(blankRankings());
 useEffect(()=>{if(!supabase){setStatus('Supabase is not configured yet.');return;}supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!supabase)return;supabase.from('teams').select('*').order('id').then(({data})=>setTeams(data||[]))},[session]);
 const scoreEntries=useMemo(()=>matchups.flatMap(m=>[m.team1_id&&m.team1_score!==''?{team_id:Number(m.team1_id),score:Number(m.team1_score)}:null,m.team2_id&&m.team2_score!==''?{team_id:Number(m.team2_id),score:Number(m.team2_score)}:null]).filter(Boolean),[matchups]);
 function updateMatchup(i,f,v){setMatchups(p=>p.map((m,x)=>x===i?{...m,[f]:v}:m))} function updateRanking(i,f,v){setRankings(p=>p.map((r,x)=>x===i?{...r,[f]:v}:r))}
 async function signIn(e){e.preventDefault();setStatus('Signing in…');const{error}=await supabase.auth.signInWithPassword({email,password});setStatus(error?error.message:'Signed in.')}
 async function recalculateStandings(){const{data:a,error:e}=await supabase.from('matchups').select('*').eq('season',2026).eq('completed',true);if(e)throw e;const s=Object.fromEntries(teams.map(t=>[t.id,{wins:0,losses:0,points_for:0,points_against:0}]));for(const m of a||[]){if(!s[m.team1_id]||!s[m.team2_id])continue;s[m.team1_id].points_for+=Number(m.team1_score||0);s[m.team1_id].points_against+=Number(m.team2_score||0);s[m.team2_id].points_for+=Number(m.team2_score||0);s[m.team2_id].points_against+=Number(m.team1_score||0);if(Number(m.team1_score)>Number(m.team2_score)){s[m.team1_id].wins++;s[m.team2_id].losses++}else if(Number(m.team2_score)>Number(m.team1_score)){s[m.team2_id].wins++;s[m.team1_id].losses++}}for(const t of teams){const{error}=await supabase.from('teams').update(s[t.id]).eq('id',t.id);if(error)throw error}}
 async function saveWeek(){setStatus('Saving Week '+week+'…');const v=matchups.filter(m=>m.team1_id&&m.team2_id&&m.team1_score!==''&&m.team2_score!=='');if(v.length!==6)return setStatus('Enter all 6 matchups and scores before saving.');if(new Set(v.flatMap(m=>[m.team1_id,m.team2_id])).size!==12)return setStatus('Each team must appear exactly once in the week.');const rows=v.map(m=>({season:2026,week:Number(week),team1_id:Number(m.team1_id),team2_id:Number(m.team2_id),team1_score:Number(m.team1_score),team2_score:Number(m.team2_score),completed:true}));let{error}=await supabase.from('matchups').delete().eq('season',2026).eq('week',Number(week));if(error)return setStatus(error.message);({error}=await supabase.from('matchups').insert(rows));if(error)return setStatus(error.message);const high=[...scoreEntries].sort((a,b)=>b.score-a.score)[0];if(high){({error}=await supabase.from('weekly_high_scores').upsert({season:2026,week:Number(week),team_id:high.team_id,score:high.score},{onConflict:'season,week'}));if(error)return setStatus(error.message)}try{await recalculateStandings()}catch(e){return setStatus(e.message)}setStatus('Week '+week+' saved. Standings and weekly high score updated.')}
 async function resetWeek(){if(!window.confirm(`Delete all saved Week ${week} results and recalculate standings?`))return;setStatus('Resetting Week '+week+'…');for(const table of ['matchups','weekly_high_scores','dirty_players']){const{error}=await supabase.from(table).delete().eq('season',2026).eq('week',Number(week));if(error)return setStatus(error.message)}try{await recalculateStandings()}catch(e){return setStatus(e.message)}setMatchups(blankMatchups());setDirtyPlayer({team_id:'',player_name:'',reason:''});setStatus('Week '+week+' reset.')}
 async function saveRankings(){const filled=rankings.filter(r=>r.team_id);if(filled.length!==12)return setStatus('Rank all 12 teams before publishing.');if(new Set(filled.map(r=>r.team_id)).size!==12)return setStatus('Each team can appear only once in the rankings.');setStatus('Publishing Week '+week+' power rankings…');let{error}=await supabase.from('power_rankings').delete().eq('season',2026).eq('week',Number(week));if(error)return setStatus(error.message);({error}=await supabase.from('power_rankings').insert(filled.map((r,i)=>({season:2026,week:Number(week),rank:i+1,team_id:Number(r.team_id),commentary:r.commentary.trim()}))));setStatus(error?error.message:'Week '+week+' power rankings published.')}
 async function saveNews(){if(!news.title.trim())return setStatus('Add a news headline first.');const{error}=await supabase.from('league_news').insert({title:news.title.trim(),body:news.body.trim()});setStatus(error?error.message:'League news published.');if(!error)setNews({title:'',body:''})}
 async function saveDirtyPlayer(){if(!dirtyPlayer.team_id||!dirtyPlayer.player_name.trim())return setStatus('Choose a team and enter a player name.');const{error}=await supabase.from('dirty_players').upsert({season:2026,week:Number(week),team_id:Number(dirtyPlayer.team_id),player_name:dirtyPlayer.player_name.trim(),reason:dirtyPlayer.reason.trim()},{onConflict:'season,week'});setStatus(error?error.message:'Dirty Player of the Week saved.')}
 if(!supabase)return <PageShell title="Commissioner"><div className="panel"><p>Supabase configuration is missing.</p></div></PageShell>;
 if(!session)return <PageShell title="Commissioner"><section className="panel commissionerAuth"><div className="panelTitle"><h3>COMMISSIONER LOGIN</h3><span>SECURE ACCESS</span></div><form className="commissionerForm" onSubmit={signIn}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primaryButton">Sign In</button></form>{status&&<p>{status}</p>}</section></PageShell>;
 return <PageShell title="Commissioner"><div className="commissionerTopbar"><div><strong>Commissioner Control Room</strong><span>{session.user.email}</span></div><button className="secondaryButton" onClick={()=>supabase.auth.signOut()}>Sign Out</button></div>
 <section className="panel commissionerPanel"><div className="panelTitle"><h3>WEEKLY RESULTS</h3><span>AUTO-UPDATES STANDINGS + HIGH SCORE</span></div><label className="weekPicker">Week<input type="number" min="1" max="18" value={week} onChange={e=>setWeek(e.target.value)}/></label><div className="matchupEditor">{matchups.map((m,i)=><div className="matchupCard" key={i}><div className="matchupNumber">MATCHUP {i+1}</div><div className="matchupTeamLine"><select value={m.team1_id} onChange={e=>updateMatchup(i,'team1_id',e.target.value)}><option value="">Choose Team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input inputMode="decimal" placeholder="Score" value={m.team1_score} onChange={e=>updateMatchup(i,'team1_score',e.target.value)}/></div><div className="matchupVs">VS</div><div className="matchupTeamLine"><select value={m.team2_id} onChange={e=>updateMatchup(i,'team2_id',e.target.value)}><option value="">Choose Team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input inputMode="decimal" placeholder="Score" value={m.team2_score} onChange={e=>updateMatchup(i,'team2_score',e.target.value)}/></div></div>)}</div><div style={{display:'grid',gap:10}}><button className="primaryButton saveWeekButton" onClick={saveWeek}>Save Week {week}</button><button className="secondaryButton" onClick={resetWeek}>Reset Week {week}</button></div></section>
 <section className="panel commissionerPanel"><div className="panelTitle"><h3>POWER RANKINGS</h3><span>WEEK {week}</span></div><p className="statusMessage">Choose each team once. Row 1 is #1, row 12 is #12. Commentary is optional.</p><div className="rankingEditor">{rankings.map((r,i)=><div className="rankingEditRow" key={i}><b>#{i+1}</b><select value={r.team_id} onChange={e=>updateRanking(i,'team_id',e.target.value)}><option value="">Choose Team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input placeholder="Commissioner comment (optional)" value={r.commentary} onChange={e=>updateRanking(i,'commentary',e.target.value)}/></div>)}</div><button className="primaryButton saveWeekButton" onClick={saveRankings}>Publish Week {week} Rankings</button></section>
 <section className="commissionerGrid"><div className="panel commissionerPanel"><div className="panelTitle"><h3>LEAGUE NEWS</h3><span>PUBLISH</span></div><div className="commissionerForm"><label>Headline<input value={news.title} onChange={e=>setNews({...news,title:e.target.value})}/></label><label>Story<textarea rows="5" value={news.body} onChange={e=>setNews({...news,body:e.target.value})}/></label><button className="primaryButton" onClick={saveNews}>Publish News</button></div></div><div className="panel commissionerPanel"><div className="panelTitle"><h3>DIRTY PLAYER OF THE WEEK</h3><span>WEEK {week}</span></div><div className="commissionerForm"><label>Team<select value={dirtyPlayer.team_id} onChange={e=>setDirtyPlayer({...dirtyPlayer,team_id:e.target.value})}><option value="">Choose team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Player<input value={dirtyPlayer.player_name} onChange={e=>setDirtyPlayer({...dirtyPlayer,player_name:e.target.value})}/></label><label>Why they were dirty<textarea rows="3" value={dirtyPlayer.reason} onChange={e=>setDirtyPlayer({...dirtyPlayer,reason:e.target.value})}/></label><button className="primaryButton" onClick={saveDirtyPlayer}>Save Dirty Player</button></div></div></section>{status&&<div className="statusBar" onClick={()=>setStatus('')}>{status}<span>×</span></div>}</PageShell>;
}
