create table if not exists public.manager_access (
  id bigint generated by default as identity primary key,
  team_id bigint not null unique references public.teams(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.trash_talk_posts (
  id bigint generated by default as identity primary key,
  author_user_id uuid not null default auth.uid(),
  team_id bigint not null references public.teams(id) on delete cascade,
  body text,
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trash_talk_has_content check (coalesce(length(trim(body)),0) > 0 or image_path is not null),
  constraint trash_talk_body_length check (coalesce(length(body),0) <= 1000)
);

alter table public.manager_access enable row level security;
alter table public.trash_talk_posts enable row level security;

create policy "Managers can read their own access row"
on public.manager_access for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt()->>'email','')));

create policy "Trash talk is publicly readable"
on public.trash_talk_posts for select
to anon, authenticated
using (true);

create policy "Linked managers can post as their team"
on public.trash_talk_posts for insert
to authenticated
with check (
  author_user_id = auth.uid()
  and exists (
    select 1 from public.manager_access ma
    where ma.team_id = trash_talk_posts.team_id
      and lower(ma.email) = lower(coalesce(auth.jwt()->>'email',''))
  )
);

create policy "Managers can edit their own posts"
on public.trash_talk_posts for update
to authenticated
using (author_user_id = auth.uid())
with check (author_user_id = auth.uid());

create policy "Managers can delete their own posts"
on public.trash_talk_posts for delete
to authenticated
using (author_user_id = auth.uid());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('trash-talk','trash-talk',true,8388608,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Anyone can view trash talk images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'trash-talk');

create policy "Managers can upload their own trash talk images"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'trash-talk'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Managers can delete their own trash talk images"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'trash-talk'
  and (storage.foldername(name))[1] = auth.uid()::text
);
