import Image from "next/image";
import { createClient } from "@supabase/supabase-js";
import PageShell from "../../components/PageShell";
import { mascotForTeam } from "../../lib/teamMascots";

export const dynamic="force-dynamic";
const ESPN_LEAGUE_ID="2145514194",SEASON=2026;
const normalize=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"");
function espnTeamName(t){if(!t)return"Unknown Team";if(t.name)return t.name;return[t.location,t.nickname].filter(Boolean).join(" ").trim()||t.abbrev||`ESPN Team ${t.id}`;}
async function getLocalData(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!u||!k)return{teams:[],rankings:[]};const s=createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}}),[{data:teams},{data:rankings}]=await Promise.all([s.from("teams").select("id,name,manager,logo").order("id"),s.from("power_rankings").select("*").eq("season",SEASON).order("week",{ascending:false}).order("rank")]);return{teams:teams||[],rankings:rankings||[]};}
async function getEspnData(){const u=new URL(`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${SEASON}/segments/0/leagues/${ESPN_LEAGUE_ID}`);for(const v of["mTeam","mStandings","mMatchupScore"])u.searchParams.append("view",v);const h={accept:"application/json, text/plain, */*","user-agent":"DirtyDozensFFL/1.0"};if(process.env.ESPN_S2&&process.env.ESPN_SWID)h.cookie=`espn_s2=${process.env.ESPN_S2}; SWID=${process.env.ESPN_SWID}`;const r=await fetch(u,{headers:h,cache:"no-store"});if(!r.ok)throw new Error(`ESPN returned ${r.status}`);const d=await r.json();return{week:Number(d?.status?.currentMatchupPeriod||1),teams:d?.teams||[],schedule:d?.schedule||[]};}
function automaticRankings(ts,schedule,currentWeek,localByName){const base=ts.map(t=>{const o=t?.record?.overall||{},g=Number(o.wins||0)+Number(o.losses||0)+Number(o.ties||0),name=espnTeamName(t),local=localByName[normalize(name)];return{espnTeamId:Number(t.id),name,manager:local?.manager||"",logo:mascotForTeam(name,local?.logo||""),wins:Number(o.wins||0),losses:Number(o.losses||0),ties:Number(o.ties||0),winPct:g?(Number(o.wins||0)+Number(o.ties||0)*.5)/g:0,pointsFor:Number(o.pointsFor||0),qualityWins:0};}),byId=Object.fromEntries(base.map(t=>[t.espnTeamId,t]));for(const g of schedule){if(!g?.home||!g?.away||Number(g.matchupPeriodId)>=currentWeek)continue;const h=byId[Number(g.home.teamId)],a=byId[Number(g.away.teamId)];if(!h||!a)continue;const hs=Number(g.home.totalPoints||0),as=Number(g.away.totalPoints||0);if(hs>as)h.qualityWins+=a.winPct;else if(as>hs)a.qualityWins+=h.winPct;}const maxPF=Math.max(...base.map(t=>t.pointsFor),1),maxQ=Math.max(...base.map(t=>t.qualityWins),1);return base.map(t=>({...t,powerScore:t.winPct*.45+(t.pointsFor/maxPF)*.40+(t.qualityWins/maxQ)*.15})).sort((a,b)=>b.powerScore-a.powerScore||b.pointsFor-a.pointsFor||b.wins-a.wins).map((t,i)=>({...t,rank:i+1}));}

export default async function Rankings(){const local=await getLocalData(),byId=Object.fromEntries(local.teams.map(t=>[t.id,t])),byName=Object.fromEntries(local.teams.map(t=>[normalize(t.name),t]));let week=1,rankings=[],source="AUTO — ESPN STATS";try{const e=await getEspnData();week=e.week;const rows=local.rankings.filter(r=>Number(r.week)===week).sort((a,b)=>Number(a.rank)-Number(b.rank));if(rows.length===12){source="COMMISSIONER EDITED";rankings=rows.map(r=>{const t=byId[r.team_id];return{rank:r.rank,name:t?.name||"Team",manager:t?.manager||"",logo:mascotForTeam(t?.name,t?.logo||""),commentary:r.commentary||""};});}else rankings=automaticRankings(e.teams,e.schedule,week,byName);}catch{const latest=local.rankings.length?Math.max(...local.rankings.map(r=>Number(r.week))):null;if(latest){week=latest;source="COMMISSIONER EDITED";rankings=local.rankings.filter(r=>Number(r.week)===latest).sort((a,b)=>Number(a.rank)-Number(b.rank)).map(r=>{const t=byId[r.team_id];return{rank:r.rank,name:t?.name||"Team",manager:t?.manager||"",logo:mascotForTeam(t?.name,t?.logo||""),commentary:r.commentary||""};});}}
return <PageShell title="POWER RANKINGS" kicker="DIRTY DOZENS POWER INDEX">{rankings.length?<><div className="weekSummary"><div><span>WEEK</span><strong>{week}</strong></div><b>{source}</b></div><div className="rankingCards">{rankings.map(r=><article className="panel rankCard mascotRankCard" key={`${r.rank}-${r.name}`}><b className="rankNumber">#{r.rank}</b><div className="rankMascot"><Image src={r.logo} alt="" width={96} height={96}/></div><div><h2>{r.name}</h2><p>{r.manager||""}</p>{r.commentary?<p className="rankComment">{r.commentary}</p>:<p className="rankComment">Record {r.wins??0}-{r.losses??0} · {Number(r.pointsFor||0).toFixed(1)} PF · Quality-win score {Number(r.qualityWins||0).toFixed(2)}</p>}</div></article>)}</div>{source==="AUTO — ESPN STATS"&&<section className="panel"><p>Automatic formula: 45% record, 40% points scored, and 15% quality of wins based on the strength of defeated opponents. A full 12-team ranking published in the Commissioner dashboard overrides the automatic order for that week.</p></section>}</>:<section className="panel emptyPage"><h2>POWER RANKINGS PENDING</h2><p>Rankings will calculate automatically once ESPN season statistics are available.</p></section>}</PageShell>;
}
